title: AI Citizen Lab
email: ai.citizen.lab@gmail.com
description: >-
  Aakanksha Tiwari is the Founder of this AI innovation hub, building ethical AI solutions for citizens.
baseurl: "" # leave this empty if deploying at root
url: "https://ai-citizen-lab.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
